  databases:
  - name: stackoverflowdb
    plan: free
    databaseName: stackoverflow_qtyy
    user: stackoverflow_qtyy_user

services:
  - type: web
    plan: free
    name: stackoverflow
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn stackoverflow.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stackoverflowdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
